const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const BOOKS=`Genesis|Exodus|Leviticus|Numbers|Deuteronomy|Joshua|Judges|Ruth|1 Samuel|2 Samuel|1 Kings|2 Kings|1 Chronicles|2 Chronicles|Ezra|Nehemiah|Esther|Job|Psalms|Proverbs|Ecclesiastes|Song of Solomon|Isaiah|Jeremiah|Lamentations|Ezekiel|Daniel|Hosea|Joel|Amos|Obadiah|Jonah|Micah|Nahum|Habakkuk|Zephaniah|Haggai|Zechariah|Malachi|Matthew|Mark|Luke|John|Acts|Romans|1 Corinthians|2 Corinthians|Galatians|Ephesians|Philippians|Colossians|1 Thessalonians|2 Thessalonians|1 Timothy|2 Timothy|Titus|Philemon|Hebrews|James|1 Peter|2 Peter|1 John|2 John|3 John|Jude|Revelation`.split('|');
const BOOK_PREFACES=['THE FIRST BOOK OF MOSES','THE SECOND BOOK OF MOSES','THE THIRD BOOK OF MOSES','THE FOURTH BOOK OF MOSES','THE FIFTH BOOK OF MOSES'];
// Scene keys use one-based book number + chapter.
const SCENE_INDEX={'1:1':'creation','1:6':'ark','2:14':'sea','18:23':'shepherd','22:6':'vision','42:2':'nativity','40:5':'hillside','43:20':'garden','66:21':'city'};
const SCENE_TEXT={creation:['The beginning','GENESIS · CREATION','Heaven, earth, and the work of ordering.'],ark:['An ark upon the deep','GENESIS · THE FLOOD','A shelter built amid a world overwhelmed by water.'],sea:['A people through the sea','EXODUS · DELIVERANCE','The sea, the wilderness, and a people on the move.'],shepherd:['The shepherd’s path','PSALMS · SONG','Pasture, water, and the imagery of care and guidance.'],vision:['The prophet’s vision','ISAIAH · CALLING','A vision of holiness and a call to speak.'],nativity:['The child at Bethlehem','LUKE · THE NATIVITY','A first-century setting for the birth narrative.'],hillside:['On the hillside','MATTHEW · TEACHING','A gathered crowd listening on the mountain.'],garden:['In the garden','JOHN · RESURRECTION','A garden tomb, morning light, and the first witnesses.'],city:['A city of light','REVELATION · VISION','The final vision uses the language of a renewed world.']};
const state={data:null,book:0,chapter:1,tags:{},lex:{},genesis:null,showStrong:true};
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function verseCount(){return state.data.books[state.book].chapters[state.chapter-1].length}
function selectedBook(){return state.data.books[state.book]}
function init(){state.data=window.__bible;if(!state.data){showLoadError();return}state.data.books.forEach((b,i)=>{const o=document.createElement('option');o.value=i;o.textContent=BOOKS[i];$('#bookSelect').append(o)});$('#bookSelect').value=state.book; $('#bookSelect').addEventListener('change',e=>{state.book=+e.target.value;state.chapter=1;render()});$('#chapterSelect').addEventListener('change',e=>{state.chapter=+e.target.value;render()});$('#previousChapter').onclick=()=>step(-1);$('#nextChapter').onclick=()=>step(1);$('#strongToggle').onclick=()=>{state.showStrong=!state.showStrong;$('#strongToggle').setAttribute('aria-pressed',state.showStrong);renderText()};$('#aboutButton').onclick=()=>showModal('aboutModal');$('#closePanel').onclick=closePanel;$('#searchOpen').onclick=()=>showModal('searchModal');$$('[data-close]').forEach(b=>b.onclick=()=>hideModal(b.dataset.close));$('#searchForm').onsubmit=search;document.addEventListener('keydown',e=>{if(e.key==='Escape'){hideModal('aboutModal');hideModal('searchModal');closePanel()}});fetch('genesis-context.json').then(r=>r.json()).then(x=>state.genesis=x).catch(()=>{});render()}
function showLoadError(){document.querySelector('#mainContent').innerHTML='<p>Scripture could not be loaded. Refresh this page to try again.</p>'}
function step(delta){let b=state.book,c=state.chapter+delta;if(c<1){if(b===0)return;b--;c=state.data.books[b].chapters.length}else if(c>state.data.books[b].chapters.length){if(b===65)return;b++;c=1}state.book=b;state.chapter=c;$('#bookSelect').value=b;render();window.scrollTo({top:0,behavior:'smooth'})}
function render(){const book=selectedBook(),chapters=book.chapters;$('#bookSelect').value=state.book;$('#chapterSelect').innerHTML=chapters.map((_,i)=>`<option value="${i+1}">Chapter ${i+1}</option>`).join('');$('#chapterSelect').value=state.chapter;$('#chapterCount').textContent=`${chapters.length} total`;$('#chapterGrid').innerHTML=chapters.map((_,i)=>`<button class="${i+1===state.chapter?'active':''}" data-chapter="${i+1}">${i+1}</button>`).join('');$$('#chapterGrid button').forEach(b=>b.onclick=()=>{state.chapter=+b.dataset.chapter;render();window.scrollTo({top:0,behavior:'smooth'})});$('#bookKicker').textContent=BOOK_PREFACES[state.book]||'THE HOLY BIBLE · KING JAMES VERSION';$('#chapterTitle').innerHTML=`${esc(BOOKS[state.book])} <span>${state.chapter}</span>`;$('#chapterSubhead').textContent=chapterSubhead();$('#chapterContext').hidden=true;$('#chapterContext').replaceChildren();showScene();renderText();loadTags();}
function chapterSubhead(){let intro=state.book===0&&state.genesis?.chapterContexts?.[String(state.chapter)];return intro?.title||'A passage in context'}
function showScene(){const key=`${state.book+1}:${state.chapter}`,kind=SCENE_INDEX[key],el=$('#illustration');if(!kind){el.hidden=true;el.innerHTML='';return}let [title,eyebrow,copy]=SCENE_TEXT[kind];el.hidden=false;el.innerHTML=`${sceneArt(kind)}<div class="illustration-copy"><span>${eyebrow}</span><h2>${title}</h2><p>${copy}</p></div>`}
function sceneArt(type){const shapes={
creation:`<defs><linearGradient id="bg" x2="0" y2="1"><stop stop-color="#102e36"/><stop offset="1" stop-color="#527a78"/></linearGradient><radialGradient id="sun"><stop stop-color="#fff0c3"/><stop offset="1" stop-color="#dab56f"/></radialGradient></defs><rect width="900" height="260" fill="url(#bg)"/><circle cx="690" cy="68" r="48" fill="url(#sun)"/><path d="M0 195 Q140 140 275 190T540 182T900 166V260H0Z" fill="#315a56"/><path d="M0 222 Q160 185 310 218T610 208T900 215V260H0Z" fill="#193e3b"/><g fill="#f5e9c9" opacity=".72"><circle cx="105" cy="56" r="2"/><circle cx="202" cy="89" r="2"/><circle cx="330" cy="44" r="1.5"/><circle cx="490" cy="82" r="1.5"/><circle cx="800" cy="112" r="2"/></g>`,
ark:`<defs><linearGradient id="sea" y2="1"><stop stop-color="#547a77"/><stop offset="1" stop-color="#183d40"/></linearGradient></defs><rect width="900" height="260" fill="#264e4c"/><path d="M0 118H900V260H0Z" fill="url(#sea)"/><path d="M0 158q45-15 90 0t90 0t90 0t90 0t90 0t90 0t90 0t90 0t90 0v102H0Z" fill="#315f5a"/><path d="M260 148 312 97h268l58 51-29 42H292Z" fill="#6a5135" stroke="#d4b878" stroke-width="3"/><path d="M335 97V69h210v28M440 69V44h54v25" fill="#936f43" stroke="#e2c88f" stroke-width="3"/><path d="M369 108v64m65-64v64m65-64v64" stroke="#d0b47b" stroke-width="3" opacity=".7"/>`,
sea:`<defs><linearGradient id="sky" y2="1"><stop stop-color="#9b8d75"/><stop offset="1" stop-color="#e4c990"/></linearGradient></defs><rect width="900" height="260" fill="url(#sky)"/><path d="M0 155Q110 60 230 155t230 0t230 0t210 0v105H0Z" fill="#2c6868"/><path d="M0 176Q110 88 230 176t230 0t230 0t210 0v84H0Z" fill="#3e8580"/><path d="M0 194Q115 112 230 194t230 0t230 0t210 0v66H0Z" fill="#193e3b"/><path d="M420 260V140q20-75 40-5l26 48 20-55 33 58v74Z" fill="#dfc99c"/><circle cx="733" cy="64" r="32" fill="#f3d695"/>`,
shepherd:`<defs><linearGradient id="hill" y2="1"><stop stop-color="#a7a077"/><stop offset="1" stop-color="#405f50"/></linearGradient></defs><rect width="900" height="260" fill="#80918a"/><circle cx="724" cy="54" r="31" fill="#edcf89"/><path d="M0 194q160-110 316 0t310-2q126-78 274-12v80H0Z" fill="url(#hill)"/><path d="M0 229q160-80 316 0t310-2q126-55 274-12v45H0Z" fill="#284b3e"/><path d="M205 191q0-30 22-30t22 30m-37-8h31" fill="none" stroke="#2b342d" stroke-width="8" stroke-linecap="round"/><g fill="#f5f0df"><ellipse cx="370" cy="201" rx="15" ry="10"/><circle cx="384" cy="198" r="7"/><ellipse cx="430" cy="213" rx="15" ry="10"/><circle cx="444" cy="210" r="7"/><ellipse cx="478" cy="196" rx="14" ry="9"/><circle cx="490" cy="193" r="6"/></g>`,
vision:`<rect width="900" height="260" fill="#202f3b"/><circle cx="679" cy="83" r="66" fill="#ddc187" opacity=".92"/><path d="M0 214 137 168l95 28 120-64 113 60 124-47 112 38 103-46 96 41v82H0Z" fill="#596762"/><path d="M552 65q80 12 121 63m-88-83q91 20 142 97m-192-91q75 1 117 39" fill="none" stroke="#f4dcab" stroke-width="3" opacity=".8"/><path d="M172 201q-15-39 9-56t34 6q20-32 40-9t7 55m-53-36v55" fill="#192b2c" stroke="#d7b66c" stroke-width="2"/>`,
nativity:`<defs><linearGradient id="night" y2="1"><stop stop-color="#162e48"/><stop offset="1" stop-color="#806746"/></linearGradient></defs><rect width="900" height="260" fill="url(#night)"/><path d="M0 206 108 148l102 58 94-73 120 74 104-65 123 64 109-57 140 64v47H0Z" fill="#293d3a"/><path d="M350 189V118l100-72 102 72v71Z" fill="#775b3b" stroke="#ddc58d" stroke-width="3"/><path d="M332 120 450 34l119 86" fill="none" stroke="#ead5a3" stroke-width="8"/><path d="M408 189v-37q42-53 82 0v37" fill="#e7c984"/><circle cx="450" cy="134" r="38" fill="#f7e5b5" opacity=".28"/><path d="M450 35 462 57 486 61 468 78 472 102 450 91 428 102 432 78 414 61 438 57Z" fill="#f5d88f"/>`,
hillside:`<rect width="900" height="260" fill="#9caa9b"/><circle cx="748" cy="52" r="34" fill="#f3d59c"/><path d="M0 179q178-104 356-2t305-9q114-68 239-18v110H0Z" fill="#68795b"/><path d="M0 214q168-74 336 0t329-5q108-51 235-18v69H0Z" fill="#395747"/><path d="M403 161v70m-14-62h28" stroke="#d7c294" stroke-width="6" stroke-linecap="round"/><g fill="#283b35"><circle cx="337" cy="190" r="8"/><circle cx="371" cy="204" r="8"/><circle cx="445" cy="191" r="8"/><circle cx="489" cy="207" r="8"/><circle cx="532" cy="188" r="8"/><path d="M329 198h17v31h-17zm34 14h17v24h-17zm73-12h17v34h-17zm44 14h17v21h-17zm44-17h17v38h-17z"/></g>`,
garden:`<defs><linearGradient id="dawn" y2="1"><stop stop-color="#293d51"/><stop offset="1" stop-color="#d0a568"/></linearGradient></defs><rect width="900" height="260" fill="url(#dawn)"/><circle cx="699" cy="100" r="54" fill="#ffe5a8" opacity=".78"/><path d="M0 199q140-83 260 0t240-1q178-76 400 3v59H0Z" fill="#294c3d"/><path d="M145 225q22-94 94-112 73 18 95 112" fill="#334636"/><path d="M232 138v87m-35-75 35 29 32-29" stroke="#c6aa73" stroke-width="5" fill="none"/><path d="M483 207q30-42 59 0v27h-59Z" fill="#e6d5b0"/><path d="M470 207q42-56 84 0" fill="none" stroke="#eedebc" stroke-width="5"/>`,
city:`<defs><linearGradient id="glow" y2="1"><stop stop-color="#9fc2c4"/><stop offset="1" stop-color="#314b59"/></linearGradient></defs><rect width="900" height="260" fill="url(#glow)"/><circle cx="702" cy="63" r="42" fill="#fff0c6"/><path d="M0 228 122 102l74 31 118-84 120 98 94-65 92 54 127-98 153 139v83H0Z" fill="#c0b899"/><path d="M305 104h287v133H305Z" fill="#f1e3be" stroke="#997e51" stroke-width="4"/><path d="M280 111 449 37l168 74" fill="#e6d4a6" stroke="#a88a56" stroke-width="4"/><g fill="#597c81"><path d="M335 131h37v47h-37zm66 0h37v47h-37zm66 0h37v47h-37zm66 0h37v47h-37z"/></g><path d="M438 237v-43q11-20 23 0v43" fill="#866846"/>`};return `<svg viewBox="0 0 900 260" preserveAspectRatio="xMidYMid slice" aria-hidden="true">${shapes[type]||shapes.creation}</svg>`}
function renderText(){const verses=selectedBook().chapters[state.chapter-1];$('#scripture').innerHTML='';verses.forEach((text,i)=>{const p=document.createElement('p');p.className='verse';p.dataset.verse=i+1;const n=document.createElement('sup');n.className='verse-number';n.textContent=i+1;p.append(n);const tagVerse=state.tags?.[String(i+1)];const words=tagVerse?.w;if(state.showStrong&&Array.isArray(words)&&words.length){const chunks=matchTaggedTokens(text,words);for(const c of chunks){if(c.ids?.length){const btn=document.createElement('button');btn.type='button';btn.className='verse-word';btn.dataset.strong=c.ids.join(',');btn.dataset.surface=c.surface;btn.dataset.ref=`${BOOKS[state.book]} ${state.chapter}:${i+1}`;btn.textContent=c.text;btn.setAttribute('aria-label',`${c.surface}, Strong’s ${c.ids.join(', ')}`);btn.onclick=()=>openWord(btn.dataset.strong.split(','),btn.dataset.surface,btn.dataset.ref);p.append(btn)}else p.append(document.createTextNode(c.text))}}else p.append(document.createTextNode(text));$('#scripture').append(p)});if(!state.showStrong)$('#scripture').querySelectorAll('.verse-word').forEach(x=>{x.replaceWith(document.createTextNode(x.textContent))})}
function normalize(s){return String(s).toLowerCase().replace(/[^a-z0-9]/g,'')}
function matchTaggedTokens(text,words){const re=/[A-Za-z0-9]+(?:[’'][A-Za-z0-9]+)*/g,found=[...text.matchAll(re)],assigned=new Map();let cursor=0;for(const row of words){let surf=Array.isArray(row)?String(row[0]??''):String(row.surface??row.word??''),ids=Array.isArray(row)?row[1]:(row.strongs||row.strong||row.ids||[]);if(!Array.isArray(ids))ids=ids?[ids]:[];const target=normalize(surf);if(!target)continue;let match=-1;for(let k=cursor;k<Math.min(found.length,cursor+5);k++){if(normalize(found[k][0])===target){match=k;break}}if(match<0)continue;assigned.set(match,ids.map(String));cursor=match+1}let out=[],pos=0;found.forEach((m,i)=>{if(m.index>pos)out.push({text:text.slice(pos,m.index)});const end=m.index+m[0].length;out.push({text:text.slice(m.index,end),surface:m[0],ids:assigned.get(i)||[]});pos=end});if(pos<text.length)out.push({text:text.slice(pos)});return out.length?out:[{text}]}
async function loadTags(){const path=`https://jsonbible.org/v1/kjvstrongs/${state.book+1}/${String(state.chapter).padStart(3,'0')}.json`;try{const r=await fetch(path,{mode:'cors'});if(!r.ok)throw Error('Could not load word links');const payload=await r.json();state.tags=payload.verses||payload;renderText();setContextSummary()}catch(e){state.tags={};$('#chapterSubhead').textContent='KJV text · Strong’s word links need an internet connection';}}
function setContextSummary(){if(state.book!==0||!state.genesis)return;const c=state.genesis.chapterContexts?.[String(state.chapter)];if(!c)return;const box=$('#chapterContext');box.hidden=false;box.innerHTML=`<strong>Chapter context · ${esc(c.title||'Genesis')}</strong>${esc(c.intro||'')}`}
function verseNote(ref){if(!state.genesis||state.book!==0)return null;let m=ref.match(/(\d+):(\d+)$/);return m?state.genesis.verseNotes?.[`${m[1]}.${m[2]}`]:null}
function openPanel(){if(window.matchMedia('(max-width:680px)').matches)$('#studyPanel').classList.add('open')}
function closePanel(){$('#studyPanel').classList.remove('open')}
async function openWord(ids,surface,ref){openPanel();$('#panelTitle').textContent=`${surface} · ${ref}`;$('#panelBody').innerHTML='<p class="muted">Opening the original-language entry…</p>';let entries=[];for(const id of ids){let local=state.genesis?.lexicon?.[id];if(local){entries.push(local);continue}if(!state.lex[id])state.lex[id]=loadLexicon(id);let x=await state.lex[id];if(x)entries.push(x)}let note=verseNote(ref);if(note&&!note.strongs.some(id=>ids.includes(id)))note=null;const body=$('#panelBody');body.innerHTML='';if(!entries.length){body.innerHTML=`<p class="muted">A Strong’s tag is attached to this word, but the dictionary entry could not be loaded. Try its direct link below.</p>${ids.map(id=>`<a class="strong-chip" href="${strongUrl(id)}" target="_blank" rel="noopener">${esc(id)} · Open Strong’s entry ↗</a>`).join(' ')}`;return}
entries.forEach(e=>{const id=e.id||e.strong||ids[0],language=(String(id)[0]==='H'?'Hebrew':'Greek'),lemma=e.hebrew||e.greek||e.lemma||e.original||'',pron=e.transliteration||e.translit||e.pronunciation||'',def=e.definition||e.def||e.gloss||e.meaning||'Definition unavailable in this record.',forms=e.kjvRenderings||e.renderings||e.kjv||'',pos=e.partOfSpeech||e.part_of_speech||'',root=e.derivation||e.root||'';const block=document.createElement('section');block.innerHTML=`<a class="strong-chip" href="${strongUrl(id)}" target="_blank" rel="noopener">${esc(id)} · ${language} Strong’s ↗</a>${lemma?`<div class="word-source" lang="${language==='Hebrew'?'he':'el'}">${esc(lemma)}</div>`:''}${pron?`<p class="word-pronunciation">${esc(pron)}</p>`:''}${pos?`<p class="kjv-forms">${esc(pos)}</p>`:''}<div class="definition-label">Lexicon range</div><p class="definition">${esc(def)}</p>${root?`<p class="root-line"><b>Root / formation:</b> ${esc(root)}</p>`:''}${forms?`<p class="kjv-forms"><b>KJV renderings:</b> ${esc(forms)}</p>`:''}`;body.append(block)});
const phrase=versePhrase(ref),first=entries[0],gloss=first?.definition||first?.def||first?.gloss||'',context=contextWindow(phrase,surface);const noteBlock=document.createElement('div');noteBlock.className='context-reading';noteBlock.innerHTML=`<b>${note?'Genesis contextual note':'My contextual reading'}</b>${note?esc(note.text):`The KJV renders this occurrence as “${esc(surface)}.” In the phrase “${esc(context)},” I take the word in the sense that fits this sentence; the Strong’s entry gives the broader range ${gloss?`“${esc(shortGloss(gloss))}”`:''}. I would keep that wider range in view without putting every dictionary gloss into this verse.`}<br><small>Study suggestion; the KJV wording above is unchanged.</small>`;body.append(noteBlock);const verse=document.createElement('div');verse.className='verse-in-study';verse.innerHTML=`<strong>${esc(ref)} · KJV</strong><br>${esc(phrase)}`;body.append(verse);const links=document.createElement('div');links.className='external-links';links.innerHTML=ids.map(x=>`<a target="_blank" rel="noopener" href="${strongUrl(x)}">Open ${esc(x)} at BibleHub ↗</a>`).join(' ');body.append(links)}
function shortGloss(s){return s.length>180?s.slice(0,177)+'…':s}
function contextWindow(sentence,word){const i=sentence.toLowerCase().indexOf(word.toLowerCase());if(i<0)return sentence;let a=Math.max(0,sentence.lastIndexOf(' ',Math.max(0,i-42))),b=sentence.indexOf(' ',i+word.length+42);if(a<0)a=0;if(b<0)b=sentence.length;return (a? '…':'')+sentence.slice(a,b).trim()+(b<sentence.length?'…':'')}
function strongUrl(id){const g=String(id).toUpperCase(),n=g.slice(1);return g.startsWith('H')?`https://biblehub.com/hebrew/${encodeURIComponent(n)}.htm`:`https://biblehub.com/greek/${encodeURIComponent(n)}.htm`}
function versePhrase(ref){let m=ref.match(/^(.*?) (\d+):(\d+)$/);if(!m)return'';let bi=BOOKS.indexOf(m[1]),ci=+m[2]-1,vi=+m[3]-1;return state.data.books[bi]?.chapters[ci]?.[vi]||''}
async function loadLexicon(id){try{const bucket=Math.floor(Number(String(id).slice(1))/1000);const url=`https://jsonbible.org/v1/lexicon/${String(id)[0]}/${bucket}.json`;const r=await fetch(url,{mode:'cors'});if(!r.ok)throw Error();const data=await r.json();return data[id]||data[String(id).toLowerCase()]||null}catch(e){return null}}
function showModal(id){const m=$('#'+id);m.hidden=false;if(id==='searchModal')setTimeout(()=>$('#searchInput').focus(),30)}function hideModal(id){$('#'+id).hidden=true}
function search(e){e.preventDefault();const q=$('#searchInput').value.trim();const out=$('#searchResults');out.innerHTML='';if(!q)return;let ref=q.match(/^(.+?)\s+(\d+):(\d+)$/);if(ref){const i=BOOKS.findIndex(b=>b.toLowerCase()===ref[1].toLowerCase());if(i>=0){goTo(i,+ref[2],+ref[3]);hideModal('searchModal');return}}const needle=q.toLowerCase();let count=0;for(let bi=0;bi<66&&count<35;bi++){const book=state.data.books[bi];for(let ci=0;ci<book.chapters.length&&count<35;ci++){const verses=book.chapters[ci];for(let vi=0;vi<verses.length&&count<35;vi++){const text=verses[vi];const at=text.toLowerCase().indexOf(needle);if(at>=0){const a=document.createElement('a');a.href='#';a.className='search-result';a.innerHTML=`<b>${esc(BOOKS[bi])} ${ci+1}:${vi+1}</b>${esc(text)}`;a.onclick=e=>{e.preventDefault();goTo(bi,ci+1,vi+1);hideModal('searchModal')};out.append(a);count++}}}}if(!count)out.innerHTML='<p class="muted">No matching KJV verses found.</p>'}
function goTo(book,chapter,verse){state.book=book;state.chapter=chapter;render();setTimeout(()=>document.querySelector(`.verse[data-verse="${verse}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}),180)}
fetch('bible.json').then(r=>r.json()).then(data=>{window.__bible=data;init()}).catch(showLoadError);
