(async()=>{
 const $=id=>document.getElementById(id),api=window.TeachingChoice;let all=[],visible=[],index=0;
 const label=g=>`${g.name} ${g.start.join(':')}–${g.end.join(':')}`;
 function render(){const g=visible[index];$('reviewPanel').hidden=!g;if(!g)return;$('reviewPassage').value=g.key;$('reviewReference').textContent=label(g);$('reviewPosition').textContent=`${index+1} of ${visible.length}`;$('reviewPrevious').disabled=index===0;$('reviewNext').disabled=index===visible.length-1;$('readPassage').href='./bible.html?ref='+encodeURIComponent(`${g.name} ${g.start.join(':')}`);const selected=api.preferred(g.book,g.start,g.matches),options=api.shortlist(g.matches,selected);$('reviewOptions').replaceChildren();
 for(const m of options){const card=document.createElement('article');card.className='recording-option'+(selected?.id===m.id?' selected':'');const h=document.createElement('h3');h.textContent=m.title;const credit=document.createElement('p');credit.textContent=`${m.teacher} · ${m.channel}`;const coverage=document.createElement('p');coverage.textContent=`Mapped range: ${m.start.join(':')}–${m.end.join(':')}`;const evidence=document.createElement('p');evidence.textContent=m.ownerReview?'Teacher or passage confirmed by Jerome.':m.teacherAttribution?'Teacher attribution based on saved source evidence or series inference.':'Teacher attributed in the saved index.';const watch=document.createElement('a');watch.href=m.url;watch.target='_blank';watch.rel='noopener noreferrer';watch.textContent='Watch recording ↗';const choose=document.createElement('button');choose.type='button';choose.textContent=selected?.id===m.id?'Selected recording':'Use this recording';choose.setAttribute('aria-pressed',String(selected?.id===m.id));choose.onclick=()=>{if(api.save(g,m.id)){render();$('choiceStatus').textContent='Saved. The Bible reader will use this recording for this passage.'}else $('choiceStatus').textContent='Could not save this choice. Browser storage may be unavailable.'};card.append(h,credit,coverage,evidence,watch,choose);$('reviewOptions').append(card)}
 $('choiceStatus').textContent=selected?'Your selected recording is shown first in the Bible reader.':'Automatic choice: Arnold first, Dennis fallback.';
 }
 function filter(){visible=all.filter(g=>String(g.book)===$('reviewBook').value);index=0;$('reviewPassage').replaceChildren();for(const g of visible){const o=document.createElement('option');o.value=g.key;o.textContent=label(g);$('reviewPassage').append(o)}render()}
 try{const [data,bible]=await Promise.all(['bible-teaching.json?v=012','bible.json'].map(async url=>{const r=await fetch(url);if(!r.ok)throw Error();return r.json()}));all=api.groups(data,bible);const books=[...new Set(all.map(g=>g.book))];for(const b of books){const o=document.createElement('option');o.value=b;o.textContent=data.books[b].name;$('reviewBook').append(o)}$('reviewBook').disabled=$('reviewPassage').disabled=!all.length;$('reviewStatus').textContent=all.length?`${all.length} passages have recording choices across ${books.length} books.`:'There are no passages with multiple recordings to review.';const ref=new URLSearchParams(location.search),requested=Number(ref.get('book'));if(ref.has('book')&&books.includes(requested))$('reviewBook').value=requested;filter();if(ref.has('chapter')&&ref.has('verse')){const point=[Number(ref.get('chapter')),Number(ref.get('verse'))];const i=visible.findIndex(g=>api.rank(g.start)<=api.rank(point)&&api.rank(point)<=api.rank(g.end));if(i>=0){index=i;render()}}}catch{$('reviewStatus').textContent='Recording choices could not load. Return to the Bible and try again.'}
 $('reviewBook').onchange=filter;$('reviewPassage').onchange=()=>{index=visible.findIndex(g=>g.key===$('reviewPassage').value);render()};$('reviewPrevious').onclick=()=>{if(index>0){index--;render()}};$('reviewNext').onclick=()=>{if(index<visible.length-1){index++;render()}};$('reviewAutomatic').onclick=()=>{if(api.save(visible[index],null)){render();$('choiceStatus').textContent='Automatic choice restored.'}else $('choiceStatus').textContent='Could not save this change.'};
})();
