const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..'),evidence=path.join(root,'verification');fs.mkdirSync(evidence,{recursive:true});const base=process.env.BIBLE_TEST_URL||'http://127.0.0.1:8766/illustrated-bible/dist/';
(async()=>{const browser=await chromium.launch({headless:true});const report={testedAt:new Date().toISOString(),base,checks:[],pageErrors:[],externalRequests:[]};
for(const [label,viewport] of [['desktop',{width:1440,height:1000}],['mobile',{width:390,height:844}]]){
 const context=await browser.newContext({viewport});await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname==='127.0.0.1')return route.continue();report.externalRequests.push(u.origin);return route.abort()});const page=await context.newPage();page.on('pageerror',e=>report.pageErrors.push(label+': '+e.message));
 await page.goto(base+'trivia.html');await page.locator('.answer').first().waitFor();assert.equal(await page.locator('dialog[open]').count(),0);assert.equal(await page.locator('#searchModal').count(),0);const bank=await page.evaluate(()=>JSON.parse(document.getElementById('embeddedBank').textContent));assert.equal(bank.questions.length,5000);assert.equal(new Set(bank.questions.map(q=>q.id)).size,5000);await page.getByRole('link',{name:'Search the Bible',exact:true}).waitFor({state:'visible'});
 await page.locator('.answer').first().click();await page.locator('#feedback').waitFor({state:'visible'});const feedbackHref=await page.locator('.verse-link').getAttribute('href');assert(feedbackHref.startsWith('./index.html?ref='));await page.screenshot({path:path.join(evidence,`${label}-trivia.png`),fullPage:true});await page.locator('.verse-link').click();await page.waitForURL('**/index.html?ref=*');await page.locator('.verse').first().waitFor();await page.getByRole('link',{name:'Bible Trivia'}).click();await page.locator('#feedback').waitFor({state:'visible'});report.checks.push(label+': trivia remains accessible, 5,000 unique questions, answer evidence links to the in-app Bible, saved progress resumes');
 await page.goto(base+'bible.html');await page.locator('.verse-word').first().waitFor();await page.locator('.bullinger-verse-button').first().waitFor();assert.equal(await page.locator('#searchModal').isVisible(),false);assert.equal(await page.locator('#aboutModal').isVisible(),false);await page.locator('#headerSearch').waitFor({state:'visible'});
 const verse=await page.locator('.verse[data-verse="1"]').evaluate(el=>{const c=el.cloneNode(true);c.querySelectorAll('.verse-number,.bullinger-verse-button').forEach(e=>e.remove());return c.textContent});assert.equal(verse,'In the beginning God created the heaven and the earth.');
 await page.locator('#headerSearch').click();await page.locator('#searchInput').fill('John 3:16');await page.locator('#searchForm').evaluate(el=>el.requestSubmit());await page.waitForFunction(()=>document.querySelector('#chapterTitle').textContent.trim()==='John 3');assert.equal(await page.locator('#searchModal').isVisible(),false);assert((await page.locator('.verse[data-verse="16"]').textContent()).includes('For God so loved the world'));
 for(const [q,title] of [['1 John 1:9','1 John 1'],['Psalm 23','Psalms 23'],['Gen 1:1','Genesis 1']]){await page.locator('#headerSearch').click();await page.locator('#searchInput').fill(q);await page.locator('#searchForm').evaluate(el=>el.requestSubmit());await page.waitForFunction(t=>document.querySelector('#chapterTitle').textContent.trim()===t,title)}
 await page.locator('#headerSearch').click();await page.locator('#searchInput').fill('John 999:1');await page.locator('#searchForm').evaluate(el=>el.requestSubmit());assert((await page.locator('#searchResults').textContent()).includes('John has 21 chapters'));assert.equal(await page.locator('#searchModal').isVisible(),true);await page.locator('#searchInput').fill('John 3:99');await page.locator('#searchForm').evaluate(el=>el.requestSubmit());assert((await page.locator('#searchResults').textContent()).includes('John 3 has 36 verses'));
 await page.locator('#searchInput').fill('In the beginning');await page.locator('#searchForm').evaluate(el=>el.requestSubmit());assert((await page.locator('.search-summary').textContent()).includes('matching verses'));assert(await page.locator('.search-result').count()>0);await page.screenshot({path:path.join(evidence,`${label}-search.png`)});await page.locator('.search-result').first().click();await page.waitForFunction(()=>document.querySelector('#chapterTitle').textContent.trim()==='Genesis 1');report.checks.push(label+': search hidden on entry, visible search control, phrases, full references, numbered books, aliases, invalid chapter/verse validation');
 await page.locator('.verse[data-verse="1"] .verse-word[data-surface="God"]').click();await page.waitForFunction(()=>document.querySelector('#panelBody').textContent.includes('H430'));assert((await page.locator('.word-source').first().textContent()).includes('א'));await page.locator('#closePanel').click();
 await page.locator('.verse[data-verse="1"] .bullinger-verse-button').click();await page.waitForFunction(()=>document.querySelector('#panelBody').textContent.includes('God. Hebrew. Elohim'));assert(await page.locator('.bullinger-verse-button').first().evaluate(el=>{const s=getComputedStyle(el);return s.backgroundColor==='rgb(255, 225, 123)'||s.backgroundColor==='rgb(245, 204, 70)'}));assert.equal(await page.locator('#studyPanel').evaluate(el=>el.classList.contains('bullinger-mode')),true);await page.waitForTimeout(300);await page.screenshot({path:path.join(evidence,`${label}-bullinger.png`)});assert((await page.locator('.bullinger-appendix-link').first().getAttribute('href')).startsWith('./appendices.html?n='));await page.locator('#closePanel').click();
 await page.locator('#bookSelect').selectOption('42');await page.locator('#chapterSelect').selectOption('1');await page.locator('.verse[data-verse="1"] .verse-word[data-surface="Word"]').first().waitFor();await page.locator('.verse[data-verse="1"] .verse-word[data-surface="Word"]').first().click();await page.waitForFunction(()=>document.querySelector('#panelBody').textContent.includes('G3056'));assert((await page.locator('.word-source').first().textContent()).includes('λόγος'));await page.locator('#closePanel').click();
 await page.locator('#bookSelect').selectOption('0');await page.locator('#chapterSelect').selectOption('6');await page.locator('#bullingerOpen').click();await page.locator('.bullinger-reference-warning').waitFor();assert.equal(await page.locator('.verse').count(),22);report.checks.push(label+': Hebrew and Greek Strong entries load locally, yellow verse links show actual Bullinger text, unresolved source reference retained at chapter level');
 await page.goto(base+'appendices.html?n=4');await page.waitForFunction(()=>document.querySelector('#coverage').textContent.includes('198 numbered'));assert.equal(await page.locator('#appendixList a').count(),200);await page.frameLocator('#appendixFrame').locator('body').waitFor();assert((await page.frameLocator('#appendixFrame').locator('body').textContent()).includes('Elohim'));await page.locator('#appendixFilter').fill('169');await page.locator('#appendixList a').first().click();await page.frameLocator('#appendixFrame').locator('img').first().waitFor();await page.waitForFunction(()=>{const i=document.querySelector('iframe').contentDocument?.querySelector('img');return i?.complete&&i.naturalWidth>0});await page.screenshot({path:path.join(evidence,`${label}-appendix-map.png`)});report.checks.push(label+': all 198 numbered appendices and two supplements indexed, text and original maps load locally');
 await context.close();}
 assert.deepEqual(report.pageErrors,[]);assert.deepEqual(report.externalRequests,[]);report.status='PASS';fs.writeFileSync(path.join(evidence,'browser-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
