const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
(async()=>{
 const root=path.resolve(__dirname,'..'),data=JSON.parse(fs.readFileSync(path.join(root,'dist/bible-teaching.json'))),bible=JSON.parse(fs.readFileSync(path.join(root,'dist/bible.json')));
 assert.equal(data.books.length,66);let lessons=0,matched=0;
 const rank=x=>x[0]*1000+x[1];
 for(let b=0;b<66;b++){
  const book=data.books[b];assert.equal(book.name,bible.books[b].name);let count=0;
  for(const l of book.lessons){assert.equal(l.book,b);assert(['Arnold Murray','Dennis Murray'].includes(l.teacher));assert.equal(l.timestampSeconds,null);assert(/^https:\/\/www.youtube.com\/watch\?v=[\w-]{11}$/.test(l.url));assert(rank(l.start)<=rank(l.end));for(const [c,v] of [l.start,l.end])assert(bible.books[b].chapters[c-1]?.[v-1]);lessons++}
  for(let c=1;c<=bible.books[b].chapters.length;c++)for(let v=1;v<=bible.books[b].chapters[c-1].length;v++)if(book.lessons.some(l=>rank(l.start)<=rank([c,v])&&rank([c,v])<=rank(l.end)))count++;
  assert.equal(book.coverage.matched,count);matched+=count;
 }
 const browser=await chromium.launch({executablePath:process.env.BIBLE_BROWSER||'/tmp/bible-browser7/chrome-headless-shell-linux64/chrome-headless-shell'}),errors=[];
 const base=process.env.BIBLE_TEST_URL||'http://127.0.0.1:8767/illustrated-bible/dist/';
 for(const [name,viewport] of [['phone',{width:390,height:844}],['desktop',{width:1440,height:1000}]]){
  const ctx=await browser.newContext({viewport}),p=await ctx.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.locator('.verse-word').first().waitFor();await p.waitForFunction(()=>document.getElementById('teachingReference').textContent.includes('Genesis'));
  assert(!await p.locator('#readerMenu').isVisible());assert(!await p.locator('#searchModal').isVisible());assert(!await p.locator('#bibleTeaching').evaluate(e=>e.open));
  await p.locator('#bibleTeaching summary').first().click();await p.locator('.teaching-link').first().waitFor();assert((await p.locator('.teaching-link').first().getAttribute('href')).includes('2F0K2ip_82U'));
  await p.locator('.verse[data-verse="3"] .verse-number').click();assert((await p.locator('.teaching-link').first().getAttribute('href')).includes('J2Ia_1jDRdc'));
  await p.locator('#readerMenuToggle').click();await p.locator('#fontIncrease').click();assert.equal(await p.locator('#scripture').evaluate(e=>getComputedStyle(e).fontSize),'22px');await p.locator('#fontDecrease').click();
  const checks=[{book:13,chapter:22,verse:10},{book:13,chapter:36,verse:23},{book:14,chapter:10,verse:44},{book:15,chapter:13,verse:31},{book:16,chapter:1,verse:1},{book:16,chapter:10,verse:3},{book:17,chapter:27,verse:7},{book:17,chapter:42,verse:17},{book:8,chapter:31,verse:13},{book:9,chapter:1,verse:1},{book:9,chapter:24,verse:25},{book:10,chapter:22,verse:53},{book:11,chapter:1,verse:1},{book:11,chapter:25,verse:30},{book:12,chapter:11,verse:47},{book:12,chapter:29,verse:30},{book:3,chapter:36,verse:13},{book:3,chapter:1,verse:1},{book:4,chapter:1,verse:42},{book:4,chapter:34,verse:12},{book:5,chapter:24,verse:33},{book:6,chapter:21,verse:25},{book:7,chapter:4,verse:22},{book:64,chapter:1,verse:25},{book:65,chapter:21,verse:16},{book:0,chapter:35,verse:29},{book:1,chapter:40,verse:38},{book:2,chapter:4,verse:35},{book:2,chapter:16,verse:10},{book:2,chapter:27,verse:34},{book:59,chapter:1,verse:1},{book:59,chapter:2,verse:6},{book:59,chapter:5,verse:14},{book:60,chapter:3,verse:17},{book:60,chapter:3,verse:18},{book:61,chapter:1,verse:1},{book:61,chapter:5,verse:21},{book:62,chapter:1,verse:13},{book:63,chapter:1,verse:14},{book:54,chapter:4,verse:22},{book:55,chapter:3,verse:15},{book:56,chapter:1,verse:1},{book:56,chapter:1,verse:25},{book:57,chapter:1,verse:1},{book:57,chapter:4,verse:16},{book:57,chapter:13,verse:25},{book:58,chapter:1,verse:1},{book:58,chapter:5,verse:20},{book:49,chapter:4,verse:23},{book:50,chapter:1,verse:1},{book:50,chapter:4,verse:18},{book:51,chapter:5,verse:28},{book:52,chapter:2,verse:17},{book:53,chapter:6,verse:21},{book:45,chapter:6,verse:12},{book:45,chapter:16,verse:24},{book:46,chapter:1,verse:1},{book:46,chapter:13,verse:14},{book:43,chapter:1,verse:1},{book:43,chapter:28,verse:31},{book:41,chapter:1,verse:1},{book:41,chapter:24,verse:53},{book:40,chapter:1,verse:1},{book:40,chapter:6,verse:44},{book:39,chapter:1,verse:1},{book:65,chapter:22,verse:1},{book:27,chapter:2,verse:20},{book:0,chapter:35,verse:27}];
  for(const x of checks){
   await p.locator('#bookSelect').selectOption(String(x.book));await p.locator('#chapterSelect').selectOption(String(x.chapter));await p.locator(`.verse[data-verse="${x.verse}"] .verse-number`).click();assert((await p.locator('#teachingReference').textContent()).includes(`${data.books[x.book].name} ${x.chapter}:${x.verse}`));
   const matches=data.books[x.book].lessons.filter(l=>rank(l.start)<=rank([x.chapter,x.verse])&&rank([x.chapter,x.verse])<=rank(l.end));
   if(matches.length){assert.equal(await p.locator('#teachingLinks > .teaching-link').getAttribute('href'),matches[0].url);if(matches[0].teacherAttribution){assert((await p.locator('#teachingLinks').textContent()).includes('Teacher attribution is inferred'));assert(await p.locator('#teachingLinks a').filter({hasText:'attribution source'}).count())}}else assert((await p.locator('#teachingLinks').textContent()).includes('No confirmed'));
  }
  await p.locator('#headerSearch').click();await p.locator('#searchInput').fill('Matthew 2:1');await p.locator('#searchForm button').click();assert((await p.locator('#teachingReference').textContent()).includes('Matthew 2:1'));await p.locator('.verse[data-verse="1"] .verse-number').click();await p.locator('#bookmarkHere').click();await p.reload();await p.waitForFunction(()=>document.getElementById('teachingReference').textContent.includes('Matthew 2:1'));assert(!await p.locator('#readerMenu').isVisible());
  await p.locator('#bibleTeaching summary').first().click();await p.locator('#teachingLinks > details').last().locator('summary').click();assert.equal(await p.locator('.teaching-coverage tbody tr').count(),66);await p.locator('#teachingLinks > details').last().locator('summary').click();await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:path.join(root,`verification/${name}-009-teaching.png`)});
  await p.locator('#bibleTeaching summary').first().click();await p.locator('#readerMenuToggle').click();await p.locator('#readingOverview').click();assert(await p.locator('#readingModal').isVisible());await p.locator('[data-close="readingModal"]').click();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await ctx.close();
 }
 // A missing optional mapping file must not prevent Bible reading.
 const ctx=await browser.newContext(),p=await ctx.newPage();await p.route('**/bible-teaching.json*',r=>r.abort());await p.goto(base);await p.locator('.verse-word').first().waitFor();await p.locator('#bibleTeaching summary').first().click();assert((await p.locator('#teachingLinks').textContent()).includes('could not load'));await ctx.close();
 const fallback=structuredClone(data);fallback.books[39].lessons=[{id:'fixtureDennis',title:'Test secondary lesson',book:39,start:[1,1],end:[1,2],url:'https://example.com/test-dennis',teacher:'Dennis Murray',channel:'Test fixture',official:true},{id:'fixtureArnold',title:'Test primary lesson',book:39,start:[1,1],end:[1,1],url:'https://example.com/test-arnold',teacher:'Arnold Murray',channel:'Test fixture',official:true}];
 const fixtureContext=await browser.newContext(),fixturePage=await fixtureContext.newPage();await fixturePage.route('**/bible-teaching.json*',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(fallback)}));await fixturePage.goto(base+'?ref=Matthew%201%3A1');await fixturePage.locator('.verse-word').first().waitFor();await fixturePage.locator('#bibleTeaching summary').first().click();assert.equal(await fixturePage.locator('#teachingLinks > .teaching-link').getAttribute('href'),'https://example.com/test-arnold');await fixturePage.locator('.verse[data-verse="2"] .verse-number').click();assert.equal(await fixturePage.locator('#teachingLinks > .teaching-link').getAttribute('href'),'https://example.com/test-dennis');assert((await fixturePage.locator('.teaching-credit').first().textContent()).includes('Dennis Murray'));assert((await fixturePage.locator('.teaching-credit').first().textContent()).includes('secondary fallback'));await fixtureContext.close();await browser.close();assert.deepEqual(errors,[]);
 const report={status:'PASS',lessons,matchedVerses:matched,totalVerses:31102,pageErrors:errors,matthewCoverage:data.books[39].coverage,markCoverage:data.books[40].coverage,lukeCoverage:data.books[41].coverage,actsCoverage:data.books[43].coverage,checks:['Arnold priority and Dennis fallback verified in isolated fixtures','all 66 books and every mapped range validated','Genesis boundaries preserved','OT/NT passage selection','search reference updates video','bookmark restore updates video','menu collapsed at entry/reload','font increase/decrease','coverage table 66 books','unmatched passage message','optional data failure leaves scripture usable','reading progress preserved','phone and desktop no overflow']};fs.writeFileSync(path.join(root,'verification/bible-teaching-test.json'),JSON.stringify(report,null,2));console.log(report);
})().catch(e=>{console.error(e);process.exit(1)});
