const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),data=JSON.parse(fs.readFileSync(path.join(root,'dist/bible-teaching.json'))),bible=JSON.parse(fs.readFileSync(path.join(root,'dist/bible.json')));
class Element{constructor(tag){this.tag=tag;this.children=[];this._text='';this._value='';this.attributes={}}set textContent(x){this._text=x;this.children=[]}get textContent(){return this._text+this.children.map(c=>typeof c==='string'?c:c.textContent).join('')}append(...xs){this.children.push(...xs)}replaceChildren(){this.children=[];this._text='';this._value=''}setAttribute(k,v){this.attributes[k]=v}get value(){return this._value||this.children[0]?.value||''}set value(x){this._value=String(x)}}
(async()=>{const storage=new Map([['illustrated-kjv-reading-v1','existing progress'],['illustrated-kjv-font-size-v1','22']]);const localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)};
const ids=['reviewStatus','reviewBook','reviewPassage','reviewPanel','reviewReference','reviewPosition','reviewOptions','reviewPrevious','reviewAutomatic','reviewNext','choiceStatus','readPassage','bibleTeaching','teachingReference','teachingLinks'];const elements=Object.fromEntries(ids.map(k=>[k,new Element('div')]));const window={localStorage};const sandbox={window,document:{getElementById:k=>elements[k],createElement:tag=>new Element(tag),addEventListener:()=>{}},URLSearchParams,location:{search:''},fetch:async url=>({ok:true,json:async()=>url.includes('bible-teaching')?data:bible})};vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(root,'dist/teaching-choice.js'),'utf8'),sandbox);const api=window.TeachingChoice,groups=api.groups(data,bible);assert(groups.length>0);
for(const g of groups){assert(g.matches.length>=2);assert(api.shortlist(g.matches,null).length<=3);assert(new Set(g.matches.map(x=>x.id)).size===g.matches.length)}
vm.runInContext(fs.readFileSync(path.join(root,'dist/teaching-review.js'),'utf8'),sandbox);await new Promise(r=>setImmediate(r));assert(!elements.reviewPanel.hidden);assert(elements.reviewOptions.children.length>=2&&elements.reviewOptions.children.length<=3);
const group=groups[0],second=elements.reviewOptions.children[1];const chosen=group.matches[1];second.children.at(-1).onclick();assert(elements.choiceStatus.textContent.includes('Saved'));assert.equal(api.preferred(group.book,group.start,group.matches).id,chosen.id);
vm.runInContext(fs.readFileSync(path.join(root,'dist/bible-teaching.js'),'utf8'),sandbox);await new Promise(r=>setImmediate(r));window.BibleTeaching.setLocation(group.book,...group.start);assert.equal(elements.teachingLinks.children.find(c=>c.className==='teaching-link').href,chosen.url);assert(elements.teachingLinks.textContent.includes('Your selected recording'));
const links=elements.teachingLinks.children.filter(c=>c.className==='teaching-link').length;const extras=elements.teachingLinks.children.find(c=>c.tag==='details');if(extras&&extras.children[0]?.textContent==='Other matching recordings')assert(links+extras.children.filter(c=>c.tag==='a').length<=3);
// Recreate the API to check saved choices survive a new page load.
vm.runInContext(fs.readFileSync(path.join(root,'dist/teaching-choice.js'),'utf8'),sandbox);assert.equal(window.TeachingChoice.preferred(group.book,group.start,group.matches).id,chosen.id);
elements.reviewAutomatic.onclick();assert.equal(window.TeachingChoice.preferred(group.book,group.start,group.matches),null);assert.equal(storage.get('illustrated-kjv-reading-v1'),'existing progress');assert.equal(storage.get('illustrated-kjv-font-size-v1'),'22');
if(!elements.reviewNext.disabled){elements.reviewNext.onclick();assert(elements.reviewPosition.textContent.startsWith('2 of'));elements.reviewPrevious.onclick();assert(elements.reviewPosition.textContent.startsWith('1 of'))}
// A saved out-of-shortlist recording stays selectable; absent recordings never replace a valid match.
const large=groups.find(g=>g.matches.length>3);if(large){assert(window.TeachingChoice.save(large,large.matches.at(-1).id));const s=window.TeachingChoice.preferred(large.book,large.start,large.matches);assert(window.TeachingChoice.shortlist(large.matches,s).some(x=>x.id===s.id));assert(window.TeachingChoice.shortlist(large.matches,s).length<=3);window.TeachingChoice.save(large,null)}
window.localStorage.setItem=()=>{throw Error('storage disabled')};assert.equal(window.TeachingChoice.save(group,chosen.id),false);window.localStorage.getItem=()=>'{invalid';assert.equal(Object.keys(window.TeachingChoice.read()).length,0);
const report={status:'PASS',duplicatePassageGroups:groups.length,booksWithChoices:new Set(groups.map(g=>g.book)).size,checks:['Review page loads actual mapping','At most three distinct options per passage','Choose and reload preserves selection','Reader uses saved choice','Automatic reset restores default','Previous/next navigation','Reading progress and font keys unchanged','Storage errors handled','Saved option remains in shortlist'],limitations:['DOM mock interaction checks; no real browser layout verification','No video playback verification']};fs.writeFileSync(path.join(root,'verification/teaching-choice-test.json'),JSON.stringify(report,null,2));console.log(report)
})().catch(e=>{console.error(e);process.exit(1)});
